name: Deploy to Lambda (myfunction)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Create ZIP package
        run: |
          zip -r function.zip index.js package.json node_modules

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # change this if using a different region

      - name: Deploy to Lambda - myfunction
        run: |
          aws lambda update-function-code \
            --function-name myfunction \
            --zip-file fileb://function.zip
